name: testing

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
      name: deploy to cluster
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout repository
          uses: actions/checkout@v3
        -
          name: build and push to docker
          uses: docker/build-push-action@v3
          with:
            username: ${{ 'victormx' }}
            password: ${{ 'Minimo8letra$' }}
            # repository: ${{ github.repository }}
            repository: ${{ 'victormx/testing' }}
            tag_with_ref: true
            tag_with_sha: true
            tags: ${{ github.sha }}
